version: '3'

services:
  webservergo:
    build: .
    container_name: webservergo
    ports:
      - 8081:8080
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
  redis:
    image: redis:alpine
    expose:
      - 6379
